name: export-and-branch-solution
#Export solution from DEV environment
# unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
  
jobs:
  export-from-dev:
    runs-on: windows-latest
    
    
  name: who-am-i  action
  uses: microsoft/powerplatform-actions/who-am-i@v0
  with:
    environment-url: ${{ secrets.environment }}
    user-name: ${{ secrets.user }}
    password-secret: ${{ secrets.password }}
    
  name: export-solution  action
  uses: microsoft/powerplatform-actions/export-solution@v0
  with:
    environment-url: ${{ secrets.environment }}
    user-name: ${{ secrets.user}}${{ secrets.user }}
    password-secret: ${{ secrets.password }}
    solution-name: ContosoInvoicingALM
    solution-output-file: out/exported/ContosoInvoisingALM.zip
    
  name: unpack-solution  action
  uses: microsoft/powerplatform-actions/unpack-solution@v0
  with:
    solution-file: out/exported/ContosoInvoisingALM.zip
    solution-folder: out/solution/ContosoInvoisingALM
    password-secret: ${{ secrets.password }}
    solution-type: 'Unmanaged'
    overwrite-files: true
    
  name: branch-solution, prepare it for a PullRequest
  uses: microsoft/powerplatform-actions/branch-solution@v0
  with:
    solution-folder: out/solution/ContosoInvoisingALM
    solution-target-folder: solution/ContosoInvoisingALM
    repo-token: ${{ secrets.GITHUB_TOKEN }}
    allow-empty-commit: true
